name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache PIP
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-pip
    - name: Cache Poetry Virtualenvs
      uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry
    - name: Install dependencies
      run: |
        pip install -U pip poetry
        poetry install
    - name: Test
      run: |
        poetry run pytest --cov=hookers -vvv
        poetry run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: false
